### ISSUE TITLE
Accompanied binary seems out-of-date

### ISSUE THREAD

**Issue by alxest** [StanfordPL/stoke#1000]
I failed to build this project on my architecture, so I tried accompanied binary to build assembly files from examples.
However, it also fails.
I added `MYPATH/stoke/bin/` to my environment variable and then typed `cd stoke/examples/tutorial && make`, but it gives me `MYPATH/stoke/bin/stoke_extract: No such file or directory`.
There is no such file in this repository, and I am stuck.
Any suggestions?

**Comment by bchurchill** [comment]
That's a binary you need to build yourself following the instructions in the README.  Are you using the docker image?

**Comment by alxest** [comment]
@bchurchill Thanks for your reply. I followed docker instructions and it works!
