### ISSUE TITLE
Target/rewrite and functions contain an undefined symbol error 

### ISSUE THREAD

**Issue by shrin18** [StanfordPL/stoke#1003]
On compilation of a random CPP code from Rosetta, g++ generates files of .s by mangled names in bins/. During passing them as a testcase to generate the output.tc, we get this error ! 

FATAL ERROR: Target/rewrite and functions contain an undefined symbol error (._ZNSt11char_traitsIcE6lengthEPKc)!
 
Does it seem to be familiar ? 
Or can anyone give any recommendations on how to solve it.

--Regards,
\Shrinish Donde.
KTH, Stockholm.

**Comment by bchurchill** [comment]
Have you tried using the `stoke_extract` tool?  Stoke doesn't consume plain .s files from arbitrary compilers.  In order to debug we'll need to be able to reproduce it and we would need to see all the commands you've run.
