### ISSUE TITLE
Undefined symbol error (.calloc_plt)

### ISSUE THREAD

**Issue by zawtom725** [StanfordPL/stoke#1009]
I am new to stoke. I've been trying to generate test cases for a function using random generation + backtracking. I got the following error:

`FATAL ERROR: Target/rewrite and functions contain an undefined symbol error (.calloc_plt)!`

My function does contain the instruction calloc_plt. I am wondering if such an instruction is supported in stoke. If not, how can I get around this issue?

**Comment by bchurchill** [comment]
Any chance your code calls the calloc function?  Or a macro that calls
calloc?  Stoke doesn't support function calls well.

Berkeley

**Comment by zawtom725** [comment]
Yes, my code calls calloc. Is it not the typical use case for stoke?

**Comment by bchurchill** [comment]
STOKE is really just a research prototype.  It's not ready for general
purpose use in the wild.

You might try writing a macro to replace calloc with a very simple inline
memory allocator.  You could try getting the support for function calls to
work, but it's very limited and you'll be mostly on your own.

**Comment by zawtom725** [comment]
Ah, I see. I will probably try to refactor my code so that callocs happen before the actual computation. Thanks.

**Comment by bchurchill** [comment]
Cool!  Let us know your experience.

**Comment by zawtom725** [comment]
I have refined my code to isolate the core computation without loops, functions call. I have a plain .s file. The function I want to optimize is is

```
complex_t make_multiple_t_2nd_loop_element(complex_t *h, complex_t *g,
                                          int i, int n, int b, int offset,
                                          complex_t s) {
  h[(i + n + offset) % n] = s;
  s = s + (g[(i + b) % n] - g[i]);
  return s;
}
```

I tried to generate some test cases for it:

```
stoke testcase
--target bin/_Z32make_multiple_t_2nd_loop_elementPCdS0_iiiiS_.s
-o test.tc
--max_testcases 1024
--def_in "{ %rbp %rsp %rdi %rsi %edx %ecx %r8d %r9d %xmm0 %xmm1 }"
--live_out "{ %rbp %rsp %xmm0 %xmm1 }"
```

And the test case generation failed with:

```
WARNING: Last reported error from StateGen: 
WARNING: Could not resize memory.
FATAL ERROR: Unable to generate testcases!
```

I have tried to set --max_memory to a large number, but it is not working. What happened? Is there a quick fix for that warning?
