### ISSUE TITLE
Some question about Markov process during stoke

### ISSUE THREAD

**Issue by HuantWang** [StanfordPL/stoke#1011]
Hello, I intend to pay attention to the Markov process constructed by stoke during the search process:
Obtaining a total Markov chain in the search process:
1) **instruction modification** in the search process, 
2)the corresponding **choose** (which of the four maybe:Opcode, Operand, swap, and Instruction), and 
3)the **time cost** for the test.
Can I get information about the above process through the existing functions?
If I can not obtain directly, I hope to get your suggestions on the code in which files need to be modified.
Any reply from you will be of great help to me, thank you！

**Comment by stefanheule** [comment]
There have been many different papers with STOKE over the years, and most do something slightly different. You'd have to look at the paper for more details. Some papers also come with artifacts that you can see exactly which version of the code was used.

In the current version, choosing a modification happens here in [search.cc](https://github.com/StanfordPL/stoke/blob/develop/src/search/search.cc#L109). The different transformations can be found in the folder [transform](https://github.com/StanfordPL/stoke/tree/develop/src/transform). Note that which transformations are actually picked can be configured using the command line (by giving weights do the different transformation or 0 to disable). The cost functions are in the folder [cost](https://github.com/StanfordPL/stoke/tree/develop/src/cost). Again, the exact cost function can be configured using the command line.

Hope this helps.

**Comment by FrancisGodW** [comment]
Thanks for your help, I have successfully obtained the required information. 

However, I encountered a problem when trying to get **the CFG of state.current**, I was imitating the logic of **stoke_debug_cfg** to extract the CFG of each current state:
But when using **stoke debug cfg --target** to parse **_Z6popcntm.s** and other examples, an error occurred: "Unable to save file!"

Hope to get your help.Thank you！

**Comment by HuantWang** [comment]
Thanks for your help! That's exciting!
