### ISSUE TITLE
stoke refuses to build under Ubuntu subsystem / Windows 10

### ISSUE THREAD

**Issue by thereald3bug** [StanfordPL/stoke#1012]
Getting the following during the compilation:

https://pastebin.pl/view/eaa36071

Microsoft Windows [Version 10.0.19041.388]
Linux version 4.19.104-microsoft-standard  (Ubuntu)

**Comment by stefanheule** [comment]
stoke isn't supported on most platforms; it should work on Ubuntu 14.04 and Ubuntu 16.04, but I would have been surprised it worked under WSL. If you want to try it out, the easiest is to use the docker container, as described in the readme.

**Comment by thereald3bug** [comment]
understood.  thanks.
