### ISSUE TITLE
How to indicate every iterations' transforming type?

### ISSUE THREAD

**Issue by HuantWang** [StanfordPL/stoke#1014]
In the polling of transform, there are always 9 types that can be executed, and the entire search space can be modified through the command line with mass -0.
But if I want to advise the type of every iterations' transform, which module do I need to modify?
Any reply from you will be of great help to me, thank you！

**Comment by FrancisGodW** [comment]
```
    TransformPools tp_;
    auto transform = WeightedTransform(tp_);
    std::vector<Transform*> transforms;
    // indicate type opcode
    transforms.push_back(new OpcodeTransform(tp_));

    for (auto t : transforms)
     {transform.insert_transform(t);}
    transform.set_seed(1); //I don't really understand the role of seed
    TransformInfo ti;
    ti = transform(state.current);
    if (!ti.success) {
      continue;
    }
```
I defined a **WeightedTransform** like this, but only one type will be run during execution, and ti.success has never been 1. 
Maybe some variables have been neglected by me.
Could you give me some advice? Thanks!

**Comment by HuantWang** [comment]
I have solved this problem by modifying the seed, thank you.
