### ISSUE TITLE
Error when using --hold_out verification without providing any testcases

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#720]

**Comment by shrin18** [comment]
I am facing some issue with this. Could you please tell me how did you resolve this ? 

FATAL ERROR: No test-cases given for hold_out verification.

**Comment by shrin18** [comment]
stoke search --target bins/_Z6popcntm.s 


WARNING: No live out values provided, assuming { %rax %rdx %rbx %rsp %rbp %r12 %r13 %r14 %r15 %xmm0 %xmm1 }
WARNING: No def in values provided; assuming { %rdx %rbx %rsp %rbp %rdi %r12 %r13 %r14 %r15 %xmm0 %xmm1 %mxcsr::rc[0] }
WARNING: Some cpu flags are not available on this hardware and will be removed:
WARNING: { syscall rdtscp pclmulqdq monitor fma movbe aes xsave avx f16c rdrand lahf_lm abm xsaveopt fsgsbase bmi1 hle avx2 bmi2 erms invpcid rtm }
FATAL ERROR: No test-cases given for hold_out verification.
stoke@88995c24d66d:~/stoke/examples/tutorial$ stoke search --target bins/_Z6popcntm.s 
WARNING: No live out values provided, assuming { %rax %rdx %rbx %rsp %rbp %r12 %r13 %r14 %r15 %xmm0 %xmm1 }
WARNING: No def in values provided; assuming { %rdx %rbx %rsp %rbp %rdi %r12 %r13 %r14 %r15 %xmm0 %xmm1 %mxcsr::rc[0] }
WARNING: Some cpu flags are not available on this hardware and will be removed:
WARNING: { syscall rdtscp pclmulqdq monitor fma movbe aes xsave avx f16c rdrand lahf_lm abm xsaveopt fsgsbase bmi1 hle avx2 bmi2 erms invpcid rtm }
FATAL ERROR: No test-cases given for hold_out verification.

(I am trying to run first command on top)
