### ISSUE TITLE
Issues when building on Ubuntu LTS 14.04

### ISSUE THREAD

**Issue by ainar-g** [StanfordPL/stoke#836]
Trying to build stoke (`6a0f6e9`) I've encountered a few issues:
1. Documentation on the dependencies on Ubuntu LTS 14.04 is slightly off. There is no g++4.9 in the default repos, you need to [add a PPA](http://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu) for that.
2. If I _don't_ install the right g++ version and set `COMPILERBINARY` to `g++-4.9` when invoking make, it will fail (obviously) and leave a broken `.depend` file. Any make command (including clean) after that seems to fail with
   
   ```
   .depend:1: *** missing separator.  Stop.
   ```
   
   The contents of the file is one big string:
   
   ```
   tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/tools/apps/src/cfg/src/cfg/src/cfg/src/cfg/src/cfg/src/cost/src/cost/src/cost/src/cost/src/disassembler/src/sandbox/src/sandbox/src/search/src/search/src/solver/src/solver/src/state/src/state/src/state/src/state/src/state/src/state/src/stategen/src/symstate/src/symstate/src/symstate/src/symstate/src/symstate/src/symstate/src/symstate/src/symstate/memory/src/symstate/memory/src/target/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/transform/src/tunit/src/validator/src/validator/src/validator/src/validator/src/validator/src/validator/src/validator/src/validator/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/validator/handlers/src/verifier/tools/io/tools/io/tools/io/tools/io/tools/io/tools/io/tools/io/tools/io/tools/io/
   ```
3. After removing `.depend` and calling `make dist_clean` I call
   
   ```
   env COMPILERBINARY=g++-4.9 make
   ```
   
   which fails with
   
   ```
   make[1]: Entering directory `/home/ainar/dev/stoke'
   src/validator/generate_handlers_h.sh src/validator handlers-tmp; \
   cmp -s src/validator/handlers.h src/validator/handlers-tmp || mv src/validator/handlers-tmp src/validator/handlers.h;
   make[1]: *** No rule to make target `iml.h', needed by `src/validator/null.o'.  Stop.
   make[1]: *** Waiting for unfinished jobs....
   rm -f src/validator/handlers-tmp
   make[1]: Leaving directory `/home/ainar/dev/stoke'
   make: *** [release] Error 2
   ```

**Comment by bchurchill** [comment]
Yeah, for ubuntu 14.04 you need to get that PPA.  The other dependency that you need is libiml-dev.  Will add these to the documentation.

The lingering .depend file is an unfortunate situation.  When it gets corrupted it breaks the whole Makefile and I don't know of a way to fix it other than manually removing it.

**Comment by bchurchill** [comment]
I've updated the documentation.  Can you confirm that installing libiml-dev resolves your issue?

**Comment by ainar-g** [comment]
Hm. Looking at your commit I see that libiml-dev already was there (right before libgmp-dev). I've tried building on another machine, and the build was successful. It might be that on my first machine the g++-4.9 in the apt-get line prevented libiml-dev from installing properly.

I'll get to the first machine in a few hours. If I'm correct and this was my mistake, I'll close the issue.

**Comment by bchurchill** [comment]
That's interesting.  At least one other machine we had configured had
this exact same dependency problem (libiml in particular), and
installing the package fixed it.  But, I didn't troubleshoot the root
cause of it not being installed, so after seeing your report I just
assumed it wasn't on the list.  It would be good to figure this one out.

**Comment by stefanheule** [comment]
I just had the same problem, and installing libiml-dev fixed the problem, so I suspect we can close this (but will wait for @ainar-g to reply).

**Comment by ainar-g** [comment]
Yep, that was it. Apparently the absence of  g++-4.9 screwed up people's dependencies and using a PPA and installing libiml-dev fixes that. I'll test the installation on some Go code tomorrow but so far it looks well.

On a side note, it might be good to mention that building stoke requires at least 8Gb of RAM. (Although that is pretty much given for a C++ project these days.)

**Comment by eloj** [comment]
I'd be interested to hear if you getting all tests passing on 'develop' (f72125024e40400) ? I've set up an Ubuntu 14.04 container (LXC) on a machine with a couple of Xeon E5-2620 v3s, and I'm getting four failed tests, the first of which is

```
[----------] 19 tests from IntegrationTest
[ RUN      ] IntegrationTest.ExamplesTutorial
Could not exec /home/me/src/EXT/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/ia32/bin/pinbin
in file Source/pin/injector_nonmac/vm_elf_loader.cpp:GenerateMiniloaderProgramForImageLoad:694
FATAL ERROR: Unspecified pintool error 65280!
stoke_testcase: ./src/ext/cpputil/include/io/abort.h:35: void cpputil::Abort::operator()(std::streambuf*, char): Assertion `false' failed.
make[1]: *** [testcase] Aborted (core dumped)
././tests/integration/integration.h:96: Failure
Value of: shell("make testcase")
  Actual: 512
Expected: 0ull
Which is: 0
```

```
$ src/ext/pin-2.13-62732-gcc.4.4.7-linux/ia32/bin/pinbin
E: Missing application name
Pin 2.13
Copyright (c) 2003-2013, Intel Corporation. All rights reserved.
VERSION: 62728 BUILDER: BUILDER DATE: Dec 26 2013
Usage: pin [OPTION] [-t <tool> [<toolargs>]] -- <command line>
Use -help for a description of options
```

```
$ ccache g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
[...]
Thread model: posix
gcc version 4.9.3 (Ubuntu 4.9.3-8ubuntu2~14.04)
```

Going through the tutorial the same failure appears during the 'stoke testcase' step:

```
$ stoke testcase --config testcase.conf
Could not exec /home/me/src/EXT/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/ia32/bin/pinbin
in file Source/pin/injector_nonmac/vm_elf_loader.cpp:GenerateMiniloaderProgramForImageLoad:694
FATAL ERROR: Unspecified pintool error 65280!
```

```
$ strace stoke testcase --config testcase.conf
[...]
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f793aaa0d40}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_IGN, [], SA_RESTORER, 0x7f793aaa0d40}, {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
clone(child_stack=0, flags=CLONE_PARENT_SETTID|SIGCHLD, parent_tidptr=0x7ffd3c32e110) = 26725
wait4(26725, Could not exec /home/me/src/EXT/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/ia32/bin/pinbin
in file Source/pin/injector_nonmac/vm_elf_loader.cpp:GenerateMiniloaderProgramForImageLoad:694
[{WIFEXITED(s) && WEXITSTATUS(s) == 255}], 0, NULL) = 26725
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f793aaa0d40}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {SIG_DFL, [], SA_RESTORER, 0x7f793aaa0d40}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=26725, si_status=255, si_utime=0, si_stime=0} ---
```

My only guess would be that it's something about my environment which this 'pintool' doesn't like, perhaps some security feature? Had problems with apparmor or SElinux before?

**Comment by ainar-g** [comment]
@eloj No, make test runs fine:

```
[==========] 742 tests from 61 test cases ran. (328853 ms total)
[  PASSED  ] 742 tests.

  YOU HAVE 22 DISABLED TESTS
```
