### ISSUE TITLE
Always check for errors after asking an SMTSolver

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#843]
All calls to is_sat and similar should be followed by a has_error call.  Right now, we don't always do this.

**Comment by bchurchill** [comment]
I think in general the error handling in the bounded validator and ddec validator could be much improved.  It's not architected carefully right now.

**Comment by stefanheule** [comment]
Okay, sounds good.  This particular problem is somewhat serious because it could actually cause unsoundness, not just bad error handling (like a bad error message or whatever).  But probably not the most likely things to happen.

**Comment by bchurchill** [comment]
Then perhaps this isn't a "wishlist" item but something that needs to get done?  What kinds of examples does such a soundness bug manifest itself?  I haven't seen this in mine, but it doesn't surprise me at all that it would come up.  Is it mostly timeouts?  What other circumstance will the solver throw an exception?

**Comment by stefanheule** [comment]
Well, I don't know, maybe it can't easily happen.  But here's what happened in my case: The formulas involved arrays, and CVC4 doesn't support those.  But instead of an error, the solver just returned false for is_sat and so every program was equivalent to every other program.

**Comment by bchurchill** [comment]
Wait, how did it involve arrays?  Your experiment doesn't touch memory?

**Comment by bchurchill** [comment]
Also, for anyone reading: CVC4 supports arrays, it's just that we don't have support to interface with that inside stoke yet.

**Comment by stefanheule** [comment]
Yeah, I'm not sure.  I'm still debugging that, because it turns out Z3 times out much more often than CVC4 for me, so I'd like to actually go back to using CVC4, since I don't need arrays.

(and yeah, that's what I meant, thanks for the clarification)

**Comment by bchurchill** [comment]
You can use --alias_strategy string, and the it won't use arrays no-matter what.  But, this method doesn't scale unless you're working with contiguous memory accesses to an array.  It would be good to figure out why expressions for memory reads/writes are being generated.

**Comment by stefanheule** [comment]
This is why: `set_heap_out(true); // FIXME: there's a bug prevening the command line argument from making it here.`

**Comment by stefanheule** [comment]
Actually, you also add the MemoryEqualityInvariant always in bounded.cc, which seems like it should only happen if heap or stack is live out?

**Comment by bchurchill** [comment]
That should actually always be there; for example, if you're trying to
prove that

movl (%rax), %edx
incl %edx

is equivalent to

incl (%rax)
movl (%rax), %edx

These programs should be equivalent if heap is not live-out, but we need
to assume that the memory is equal in the beginning to make this proof work.

So, I guess this is the good answer for "why are there still arrays when
I don't have memory?".  I suppose if you want to use CVC4 you'll also
need to use --alias_strategy string.

**Comment by stefanheule** [comment]
Ah, thanks for the explanation, that makes sense.

**Comment by bchurchill** [comment]
This can actually be serious.  It can hide a typechecking error where the solver doesn't actually run at all.  Gonna upgrade this.  Do you know where you've seen this check missed?  It's only the string memory model stuff, right?

**Comment by stefanheule** [comment]
Just grep for "is_sat", there aren't that many occurances.  It's definitely with the string aliasing, but also in cutpoints.cc, I think.

**Comment by bchurchill** [comment]
I won't fix the cutpoints.cc ones, mostly because I've totally rewritten that and I'll merge in a new one soon enough (which doesn't use the solver at all actually).  Also, it's okay to be unsound in cutpoints.cc.  Everything that it does gets checked inside of ddec.cc.
