### ISSUE TITLE
Allow direct execution of binaries without wrapper script

### ISSUE THREAD

**Issue by jrkoenig** [StanfordPL/stoke#848]
Currently the wrapper script (bin/stoke) sets LD_LIBRARY_PATH so z3 and cvc4 can be found. This means `gdb stoke search ...` doesn't work as expected. The fix is to use RPATH/RUNPATH in the executable via linker flags, and use `readlink("proc/self/exe")` to find `pin` in stoke_testcase. This would allow us to `gdb stoke_search ...` for easier debugging.

**Comment by stefanheule** [comment]
This is great, thanks @jrkoenig!
