### ISSUE TITLE
validator support for these opcodes

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#863]
to implement manually:
- pmovmskb
- shldq 
- shrdq
- movlpd

**Comment by bchurchill** [comment]
Just as the fuzz tester handles uninterpreted functions gracefully, it also handles undefined behavior gracefully (an unconstrained variable is just an uninterpreted function with no argument).  I removed the code that prevented us from checking potentially undefined registers/flags.  This surfaced some errors in the flags of shift and rotate instructions, similar to #648.  I fixed these... hopefully there won't be more.

**Comment by stefanheule** [comment]
Not quite, an unconstrained variable is not the same as an uninterpreted function with no arguments.  The latter is required to be the same if used in two different contexts, the former is not.  In some cases the bahavior will be the same, but in many it will not.  An unconstrained variable is truly not giving any information, wheras with uninterpreted functions we can at least enforce functional requirements (same inputs will give same output, even if the output is unknown), and we bound what the output can depend on.

**Comment by sharmar** [comment]
In a model produced by an SMT solver, an unconstrained variable can be assigned only a unique value. So even in different contexts it would have the same value as given by the model. Or am I missing something here?

**Comment by stefanheule** [comment]
@bchurchill implemented a few circuit outputs as fresh unconstrained variables.  Every time that circuit runs, there is a new variable.  If instead we had used an uninterpreted function with the right, then we would get more information, e.g. that two invocations in the same state yield the same output.

Uninterpreted functions are great for things we cannot precisly specify, or don't want to for some reason.  Unconstrained variables are great to use for undefined outputs (as per the Intel manual), but they are definitely not the same as an UIF without arguments.

**Comment by bchurchill** [comment]
I don't understand the purpose of this discussion.  As far as I know, any semantic difference between "uninterpreted function with zero arguments" and a "fresh, unconstrained variable" will not cause this approach to fail.

I do think they're the same as a UIF.  We only get extra information from UIFs if we use the same UIF multiple times in the same SMT invocation.  If we used the same variable in multiple places in the SMT invocation, we also would get the same "extra information", i.e. that the two variables have the same value.  Using a fresh, unconstrained variable is equally useful for things we cannot or do not want to specify precisely.  In both cases, each SMT invocation searches for models (i.e. a definition of the function, or a value for the variable), and each SMT invocation is different.  The only difference is that the UIFs we use are generally named and can be shared across a target/rewrite, whereas the fresh variables don't get names and are only used once.

However, it truly does not matter.

**Comment by bchurchill** [comment]
Reopening because I need to fix some new bugs in the test suite.
