### ISSUE TITLE
sandbox/validator bugs

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#868]
These instructions have different outputs from Sandbox/Validator:

```
xchgb (%rax), %al
xchgl (%r11d,%ebx,1), %r11d
xchgb 0x64(%rdx), %dh
xchgb 0x5(%r11d,%ebx,1), %bl
xaddb %dh, -0x10(,%rdx,2)
xaddb %dh, -0x10(,%rdx,2)
```

**Comment by stefanheule** [comment]
Yep, saw that.  I will fix the output for memory soon, which should help us understand these.

**Comment by bchurchill** [comment]
actually, I almost have a fix for this.  I should be committing soon.
