### ISSUE TITLE
ddec tests are disabled due to performance problems

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#872]
After talking to @bchurchill, I disabled all ddec tests (see https://github.com/StanfordPL/stoke/commit/911b3e67f24164cc252ae8c40225cba2636d12cb).  Once the speed problems have been fixed, we should enable them again.

**Comment by bchurchill** [comment]
Just to provide an update -- realistically, this will get done once DDEC is truly in a stable state.  There are research challenges beyond the implementation ones.  But, I am committed to doing this.  In the meantime, if anyone wants to use DDEC on something shoot me an email and I'll give an update on the latest and greatest :-)
