### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#874]
```
[  FAILED  ] ValidatorCmovSetCCTest.SetCCIdentity
[  FAILED  ] ValidatorCmovSetCCTest.CmovCCIdentity
[  FAILED  ] ValidatorCmovSetCCTest.CmovSetEquivalent
[  FAILED  ] ValidatorMemoryTest.Read4BytesFrom3Words
```

@bchurchill, do you know why these are failing.  Looks like the last changes were made by you.

**Comment by bchurchill** [comment]
As discussed, these couldn't be reproduced and aren't related to my changes.  I suspect that something is going on inside the Cvc4Solver.
