### ISSUE TITLE
consistent mechanism to find STOKE's path

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#890]
There are now many components of STOKE that need to introspectively find its own path.  These include the pintool for stoke_testcase; the fixtures for the test suite; the ./stoke script itself; and the strata handlers.  It would be easy to create a unified mechanism that would do this all the same way that could be easily configured with the configure script, if the user wanted to do anything non-default.

**Comment by stefanheule** [comment]
How would that work with the ./configure script?  I'm not sure I see a particularly easy solution.

**Comment by bchurchill** [comment]
Two ways.  By default, the configure script would find its current
location (like the ./stoke script currently does) and save this into a
variable.  Alternatively, the user would specify a path.  In both cases,
this variable would be passed to the preprocessor via a flag to g++. 
Then the code can use this preprocessor variable.

**Comment by stefanheule** [comment]
I see.  That method does have the downside that moving the binary to a new location requires recompilation, which is a bit awkward and definitely unexpected.  The current mechanism works regardless of whether the bin folder got moved or not.

**Comment by bchurchill** [comment]
There's two separate things here: (1) creating a consistent mechanism, which could be what we have now but shared across multiple pieces of code; and (2) what that mechanism is.  I'm open to other suggestions on (2).

The whole point is this: right now, all the mechanisms do different things.  When it comes to moving the bin folder, some work (e.g. strata's), but some fail (e.g. the "stoke" script itself and the test suite).  If you move the bin folder to another directory (e.g. the parent directory of the stoke repo) and run bin/stoke_test, you get a segfault.  This isn't something that we actually care about being able to do anyway, seeing as we never test this.

**Comment by stefanheule** [comment]
The stoke script should also work, unless I'm misunderstanding what it does.  I don't know what mechanism the test suite uses, though.  In any case, I totally agree that this would be a good refactoring, I just don't know of a good way to do it that preserves the ability to move the bin directory.
