### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by josephwinston** [StanfordPL/stoke#901]
I'm on Ubuntu 14.04 LTS that has g++4.9 installed by following https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04.  The other dependencies were installed as shown in the `README.md`. 

``` bash
$ sudo apt-get install bison ccache cmake doxygen exuberant-ctags flex g++-4.9 g++-multilib gcc-4.9 ghc git libantlr3c-dev libboost-dev libboost-filesystem-dev libboost-thread-dev libcln-dev libghc-regex-compat-dev libghc-regex-tdfa-dev libghc-split-dev libjsoncpp-dev python subversion libiml-dev libgmp-dev
```

 I'm working on the develop branch at commit https://github.com/StanfordPL/stoke/commit/f850d1e72956ddecc3bf549094be8e52b282c01c.  Are these failures expected?

```
[----------] Global test environment tear-down
[==========] 709 tests from 60 test cases ran. (281466 ms total)
[  PASSED  ] 700 tests.
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] IntegrationTest.SandboxRip
[  FAILED  ] ValidatorCmovSetCCTest.SetCCIdentity
[  FAILED  ] ValidatorCmovSetCCTest.CmovCCIdentity
[  FAILED  ] ValidatorCmovSetCCTest.CmovSetEquivalent
[  FAILED  ] ValidatorMovapdTest.Align8WithOriginalBad
[  FAILED  ] ValidatorMovapdTest.Aligned16WithOriginalAvx2Bad
[  FAILED  ] ValidatorMemoryTest.Read4BytesFrom3Words
[  FAILED  ] ValidatorMemoryTest.ReadFromOverlappingWritesOffset2
[  FAILED  ] ValidatorMemoryTest.ReadFromOverlappingWritesOffset3

 9 FAILED TESTS
  YOU HAVE 15 DISABLED TESTS
```

**Comment by stefanheule** [comment]
Not really, no.  Though we do have problems with the `ValidatorCmovSetCCTest.*` tests failing intermittenly lately, and haven't looked into that issue too much.  Just to double-check, could you re-run the tests one or two more times and see if any of the failures go away?  If not, could you post the full test output so that we might have a chance of understanding what's going on (either here, or pastebin, or emailing it o us)?

Finally, what CPU you are using?  STOKE is a little sensitive to what CPU is being used.

**Comment by stefanheule** [comment]
By the way, you can find out what CPU you have with the following command: `cat /proc/cpuinfo | grep "model name"`

**Comment by josephwinston** [comment]
I'm running on a VM.  The goal was to build stoke and then package it in a Docker Container for use.

``` bash
$ cat /proc/cpuinfo | grep "model name"
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
model name      : Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz
```

The gist is here: https://gist.github.com/josephwinston/76611f6c3704050392c6364bb48769e0

**Comment by bchurchill** [comment]
You can safely ignore these errors.  They mostly come from the validator failing with an error from the SMT solver.  STOKE should behave soundly in this situation, although you might loose out on verification opportunities.  I suspect most of the failures relate to #905.

**Comment by stefanheule** [comment]
We will work on #905 and try and fix these testing failures.  I'm closing this ticket for now.
