### ISSUE TITLE
Move wiki content into an FAQ in the README for better discoverability.

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#902]

**Comment by stefanheule** [comment]
Hey @bchurchill, could you take a look at what I wrote in [the FAQ](https://github.com/StanfordPL/stoke/#user-faq)?  In particular about how to work with `stoke replace`.  That's a workaround I recently found, but I was wondering if there are better things I can do.  Thanks.

**Comment by bchurchill** [comment]
Looks fine to me.  I like your workaround.  What I was doing, which is
probably less efficient, was to keep around a .o file with one function
having the right name but full of nops.  Then I would link that into the
binary I wanted to run "stoke replace" with instead of the real function.
