### ISSUE TITLE
Problems building on Ubuntu-16.04

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#921]
- pin doesn't pick the right compiler
- problem with boost_regex; still investigating.

**Comment by stefanheule** [comment]
Make sure you build on all the work I've already done: https://github.com/StanfordPL/stoke/issues/887

**Comment by bchurchill** [comment]
What's already been done?  I'm working off develop.  I've fixed the pin issue, but I'm having the same issue as #915.

**Comment by stefanheule** [comment]
Most of those issues are solved, see the branch.  I believe I was trying to get a more recent version of CVC4 to make it work with gcc5.3 at the end, but didn't finish that quite yet.  Let's close this as a duplicate.

**Comment by bchurchill** [comment]
I'm working off g++4.9 btw, so I wouldn't encounter the same issues as you would.

**Comment by stefanheule** [comment]
I think it would be much better to use the default compiler, not something pretty old.

**Comment by bchurchill** [comment]
We should be able to work with both.  Both of our tickets are worth doing.

**Comment by bchurchill** [comment]
Question for you: it looks like all of the boost regex functionality is built into g++-4.9 (and higher).  Do you have any objection to just replacing the boost dependency with the standard library option?

**Comment by bchurchill** [comment]
FWIW, and this is a good example: the pin issues we're solving are actually complementary.  I was noticing that the wrong compiler (i.e. not the one in the .stoke_config file) was being passed to pin.  That's important if you want to choose your compiler (be it 4.9 or otherwise).  But, your change is necessary to compile for the newer ones, of course.

**Comment by bchurchill** [comment]
Ok, I didn't quite fix this, but I fixed a lot of makefile bugs.  In fact, we can now build with 4.9 on 16.04, but can't run the test suite (so I can't be sure if it really works!).  The only holdout was libjsoncpp, sadly.   I think it's an ABI problem, which makes me suspect you're right: we should ditch 4.9 entirely.  There might be some fundamentally incompatible changes, so we might have to upgrade our lab systems at the same time.

**Comment by stefanheule** [comment]
Cool, thanks.  And yeah, I definitely don't need boost-regex.
