### ISSUE TITLE
tool for verified register canonacalization

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#922]
I'm looking to make a tool that takes a code fragment and renames its registers in a canonical way (e.g. make the first register 'rax', the second 'rcx', and so on).  Then we use the validator to make sure we didn't do anything bad, because some instructions might side-effect a particular register.

Question: do we want to add this to the STOKE code base (i.e. do we think others will reuse it?) or should we keep it out of develop?

**Comment by stefanheule** [comment]
This sounds like a fine tool to have in develop.  We already have a number of tools that are probably relatively specialized (some of the "stoke_debug_*"), and they are usually self-contained enough that they don't cause any trouble in terms of maintaining them.  If this tool, or another one, becomes to cumbersome to maintain, we can always move it into a separate branch at that point.

**Comment by stefanheule** [comment]
And yeah, this does sound potentially useful, so I'd say go for it!
