### ISSUE TITLE
iml.h build issue missing on centOS 7

### ISSUE THREAD

**Issue by Ch0ronomato** [StanfordPL/stoke#924]
I'm having a build issue when running make on CentOS 7. The issue is similar to #836 . It seems like the issue maybe related to integer matrix lib not being installed / not being installed correctly? 

I understand cent isn't the support distro, but is there any guidance I maybe able to receive from the stoke team?

**Comment by stefanheule** [comment]
I doubt we will be able to assist, because none of us are using CentOS unfortunately, but we can try.  What exactly is the error message you see?  Have you installed all ensured that all dependencies are installed (I don't know how to do this on CentOS, but hopefully there is a package manger to do this easily)?

**Comment by Ch0ronomato** [comment]
Hey Stefan,

I figured, but I wanted to reach out to see if it was worth a shot. 

make[1]: **\* No rule to make target `iml.h', needed by`src/validator/null.o'.  Stop.

I have all the packages install that is outline in the readme, at least the equivalent versions. However, I'm worried about integer matrix library. Do you know of a way I can test the install?

Yes, CentOS uses yum

**Comment by stefanheule** [comment]
Yes, it sounds like the library was not installed.  On Ubuntu, the dependency is called libiml-dev, and the particular file that make is complaining about, is located here: `/usr/include/iml.h`.  I don't know how to install this dependency on CentOS, but hopefully doing so will solve this issue.

**Comment by Ch0ronomato** [comment]
Yeah, iml is missing. But it looks like iml isn't anywhere in the package repo for CentOS, so maybe I'll have to build iml from source. I'm assuming it should be the same? Is there a particular version I should get?

This issue can be closed, since cent isn't officially supported by the stoke team, but I can update progress on it as I go along if you want?

**Comment by stefanheule** [comment]
On Ubuntu 14.04 (which we currently use for development), we have version 1.0.3-5 of libiml-dev installed.  Okay, I will go ahead and close this issue, but feel free to update if you find out more, others might appreciate it.

Thanks and good luck!

**Comment by bchurchill** [comment]
If you like, this is a dependency you can remove if you're willing to
forego the ddec validator.  Just comment out the uses of it in null.h and
null.cc, and tweak dependent code (should be very little) so it compiles.

**Comment by Ch0ronomato** [comment]
Good news! I got it to work!

I had to build iml from source wich was a bit of a pain, but now stoke compiles. However, when running the tutorial, I get the following error on the stoke testcase --config testcase.conf command:

/home/ischweer/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/ia32/bin/pinbin: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

Can I get some assistance here? Do I need to open another issue?

**Comment by stefanheule** [comment]
We can talk more here.

I don't know exactly what that error message is about, the library should be available in this directory: https://github.com/StanfordPL/stoke/tree/develop/src/ext/pin-2.13-62732-gcc.4.4.7-linux/intel64/runtime/cpplibs

Is it not there? Are the symlinks broken?

**Comment by Ch0ronomato** [comment]
They are there, but it's not being found. When I ran stoke, I added the bin directory the path variable. Do I need to add to my ld path for the libstdc++11.so file?

**Comment by bchurchill** [comment]
I've never encountered this problem before, but that seems like a good guess.  I would really recommend running stoke on Ubuntu 14.04; we've noticed that our software isn't very portable because only a handful of us develop it in only a handful of environments.  Ubuntu 14.04 with gcc-4.9 is really the only place we're confident it's going to work at the moment.

**Comment by Ch0ronomato** [comment]
The reason I'm on centos to begin with is just because of resources. I'm sure I boot a vm for ubuntu. However, I would really like to try to get this working since it's for my research group and we develop on centos mostly. So before I give up, could I be given a description of how pin is used, and maybe a description of how the path is determined? The issue is more than likely in the environment.

Also, I have quite a few little changes made to the build process. Is it possible I could open a PR against the repo? Perhaps in a separate branch?

Thank you two so much for the assistance! Very excited to start working with the repo.

**Comment by stefanheule** [comment]
PIN is used in STOKE to capture test-case information during the run of a binary.  Given a regular binary, STOKE can obtain the CPU/memory state right before a given function starts executing (using PIN), and this information is then written to a testcase file.

To this end, STOKE includes a PIN tool (a program building on top of PIN), and it can be found in src/ext/pin.../source/tools/stoke, including the makefile to build it.  This tool is then invoked via the code in tools/apps/stoke_testcase.cc (function trace).

I haven't implemented any of this, so I'm not really familiar, but this information should be a good starting point.

**Comment by stefanheule** [comment]
Yes, you are welcome to open pull requests against our repository.  You can do so by forking it, and then opening a pull request against https://github.com/StanfordPL/stoke.  We cannot guarantee that we will be merging all pull requests, but if they are generally useful we will certainly consider them!

**Comment by bchurchill** [comment]
If you don't want the testcase extraction stuff, this is another thing you
can remove.  I'm somewhat familiar with our pin tool but I don't understand
the build system for it -- it's one of the few things Stefan and I
inherited but thankfully haven't had to touch yet!

**Comment by Ch0ronomato** [comment]
Hey @bchurchill and @stefanheule 

I was able to fix the issue. It looks like on this machine (maybe centos in general) we need to add to the LD_CONFIG_PATH (or just move these libs into /usr/lib) to get things to run. After that, it was smooth sailing. 

Success!

I will fork and open a PR. No need to merge if it's insufficient. :)

**Comment by stefanheule** [comment]
Awesome, glad to hear it all worked out.

**Comment by bchurchill** [comment]
Were you able to make everything work on centos?  With 'make test' reporting all (or nearly all) success?

**Comment by Ch0ronomato** [comment]
Hey @bchurchill 

Yes I was. I don't get any failing tests. 

Ian

**Comment by bchurchill** [comment]
Great!   Glad to hear it.
