### ISSUE TITLE
Where does stoke save its results from earlier cycles?

### ISSUE THREAD

**Issue by travisdowns** [StanfordPL/stoke#941]
As far as I can tell, with a configuration like:

```
# (actual numbers, much, much larger)
--timeout_iterations 5000
--cycle_timeout 1000
```

stoke will try up to 5,000 proposals, but restart after every 1,000. When I cancel the run with `^C`, however, it only seems to output the lowest cost/lowest correct for the last cycle? I was doing a run where the initial cost for the input function was 52, and in a fairly early cycle it reported getting down to 40 lowest/42 correct. Later on the cycle restarted several times and when I hit `^C` it happened to be on 50/50 but it just output that solution from the current cycle. 

Shouldn't it output the best solution across all cycles, in this case the 42-cost one?

Also, it's not clear to me when a stoke run _stops_. Often it stopped when it found any correct rewrite that was an improvement over the default, but since I changed the cost function to `correctness * 5 + latency * 5 + binsize` it seems to keep going and restart cycles even after finding a cheaper function than the input.

**Comment by stefanheule** [comment]
If a cycle finishes with a rewrite that is correct and lower cost, STOKE will stop and save it.  It will NOT continue with another cycle, so what you describe should not happen.

STOKE will stop when it finds a correct rewrite of cost 0, regardless of where in the search it is.  It will also stop at the end of a cycle if the rewrite is correct, and has a lower cost than the initial program.

You may want to look at `--results`, which allows you to save ALL correct rewrites in a directory, not just the last one.

**Comment by travisdowns** [comment]
Thanks Stefan, I think `--results` was what I was looking for. About the described behavior, it's possible I somehow misread the progress reports. I'm `tee`ing everything to a file now so I can go back and check if this happens again. When it occurred the output exceeded my terminal buffer so I couldn't scroll back.

**Comment by travisdowns** [comment]
As it turns out my confusion was about the word **correct** in the output. I did indeed see something like "Lowest correct cost: 40", but as I understand it now, **correct** just means "the correctness function returned zero" not "... and validated". So the 40-cost solution stoke was talking about happened to be correct based on the `--training_set`, but later failed validation against the holdout set.

This is actually a bit of an limitation of the current UI - sometimes the code stoke is showing you in the "lowest known correct cost" is just the target code, which is both **correct** and **validated** (by definition). Other times, it is showing you some rewrite that is **correct** (in the stoke UI sense) but hasn't been validated yet. Similarly, this leads to output like:

```
Lowest cost:                   41
Lowest correct cost:           25
```

Semantically, this is impossible, since the "lowest cost" solution can't have a higher cost than the "lowest cost, correct solution" since the solutions eligible for the latter are a subset of the former. This happens, of course, because the "lowest correct cost" is allowed to include the target, while the "lowest cost" line **only** includes rewrites. Personally I think it would be much clearer if it were 3 lines:

```
Lowest cost:                   41
Lowest correct cost:           49
Target cost:                   25
```

The `Target cost` would of course never change for the duration of the run - but it's really important to see how the rewrite costs compare to the target (especially when iteratively running the optimizer, as you might lose track of what the current target and its cost is). In the same vein, it would be awesome if the progress reports actually showed you when some displayed code is simply the target.

About `--rewrite` it seems like it doesn't save the _final_ (best) rewrite, which is a bit unfortunate. Normally I'd expect the final re-write to show up like the others. It's also unfortunate because the rewrites there have the handy renumbering functionality that the `--out` file doesn't have. So when running stoke repeatedly, you have to copy the `--out` file out of the way every time to avoid it being clobbered. `--results` doesn't have that issue.

**Comment by stefanheule** [comment]
I agree, the UI can be confusing, I've definitely been confused by it in the past.  Improving it would be nice.

I also agree that having the last rewrite be save to --results would be useful.  That should be an easy change though, feel free to open a ticket for that.
