### ISSUE TITLE
Example in README.md incorrectly uses rax for --def_in

### ISSUE THREAD

**Issue by travisdowns** [StanfordPL/stoke#942]
The .config file for the synthesize example in the main README.md has:

    --def_in "{ %rax %rdi }" # The registers that are defined on entry to the target

However, `rax` is not defined on function entry in the x86-64 ABI, and including it wrongly allows stoke to use it to come up with faulty re-writes. This is especially prevalent if you generate your test cases in a loop, since `rax` is used to hold the result so it may very well still contain the result of the previous call, so stoke may cleverly use the value of the prior invocation to calculate the return value for the current one!

The correct `--def_in` for that function is `%rdi` only, or perhaps `%rdi %rbp %rsp` if you think the function may care about the stack (this one doesn't).

**Comment by bchurchill** [comment]
I think you're right that it's a bug, although I haven't seen the example fail because of this.  Have you?  Either way, feel free to open a PR.

**Comment by travisdowns** [comment]
I have seen an examples fail because of this, locally, yes.

It depends entirely on how the testcase generation program is compiled. As a trivial example, if you have a 1-liner function: `return 0;` and your testcase program happens to always enter with `rax == 0`, stoke will quickly find the trivial solution `retq` if you include `rax` in `def_in`.  If your test case program enters with some non-zero value in `rax` on other hand, it will just find the correct solution `xor %rax, r%ax; retq`. 

On the other hand, remove `rax` from `def_in` and it will always find the correct solution.

Just to be clear, I never found it with the `popcnt` example in the `README` - because I never even ran the example, and because it has a trivial simplification that doesn't get much benefit from induction on the previous result. With other trivial programs you can easily get bad results.
