### ISSUE TITLE
stoke testcase succeeded but did not generate .tc file

### ISSUE THREAD

**Issue by jamesalbert** [StanfordPL/stoke#954]
First of all, specs:

OS: ubuntu 14.04 64-bit using Vagrant
GCC: 4.9.3
Stoke: latest (develop)

The problem: test cases are not getting generated from `stoke testcase --config testcase.conf`

steps to reproduce:

```bash
stoke extract -i ./sana -o bins
stoke testcase --config testcase.conf
```

`testcase.conf`
```
##### stoke testcase config file

--bin ./sana
--functions bins

-o simpleRun.tc

--fxn _ZN10TabuSearch9simpleRunERK9AlignmentdRy
--max_testcases 1024
```

It ran for somewhere between 4-8 hours, I didn't think to time it but I left it running overnight. The binary ran and exited fine and everything looks normal, but `simpleRun.tc` was never generated. I'm not sure how much info you need so let me know if I should add anything. I've seen some issues here with `testcase` and dynamic memory not working properly. This is a big project and I feel dynamic memory may be the least of my worries complexity-wise.

**Comment by bchurchill** [comment]
To effectively debug this we would need to run the pin tool on the binary ourselves and see what's going on.  Taking a step back though, could you share your goals of what you're trying to do?  If you have a big project, the best bet for superoptimization is to profile your code and find one or two small loops that take a lot of time that you want to superoptimize.  STOKE isn't at the point where you can point it at a large binary and have it just work.  If your binary is taking 4-8 hours to run (even under instrumentation), it's probably too big for us to do much with.

**Comment by jamesalbert** [comment]
That makes a lot of sense actually. It is a big project, but I'm passing _ZN10TabuSearch9simpleRunERK9AlignmentdRy to --fxn in an attempt to optimize simpleRun (which is the small loop you mentioned).

I think I understand what you're saying though. I should isolate simpleRun and its reference member functions (etc), compile it to its own binary, then run stoke on that?

I don't think we need to do the pin tool test, I think you're right it's just too much for what I'm trying to accomplish. Thanks for the help.
