### ISSUE TITLE
issue loading shared libraries

### ISSUE THREAD

**Issue by jamesalbert** [StanfordPL/stoke#958]
Should be simple enough to diagnose. Here's how I'm compiling:
```
gcc -std=c11 -O3 -fno-inline src/mini.c -g -lm -lcalg -lncurses -lpthread -I/usr/local/include/libcalg-1.0/libcalg -o bin/mini
```

I'm able to run it as `./bin/mini`, but when I run it through `stoke testcase` I get:
```
bin/mini: error while loading shared libraries: libcalg.so.0: cannot open shared object file: No such file or directory
```

Same error I'd get if my $LD_LIBRARY_PATH isn't set, but I have it set (I'm able to run it normally). I've also tried:

```
LD_LIBRARY_PATH="/path/to/lib" stoke testcase --config testcase.conf
```

but to no avail. Anyone know where I'm messing up?

edit:

**specs:**
OS: Ubuntu 16.04
Stoke: latest

`testcase.conf`:
```
--functions bins
--bin bin/mini
--args "input/yeast.gw input/human.gw"
-o mini.tc
--fxn main
--max_testcases 1024
```

**Comment by yzhao30** [comment]
Can you verify libcalg.so.0 exists with `locate libcalg.so.0`?

**Comment by jamesalbert** [comment]
Yes I can
```
vagrant@vagrant:~/stoke$ locate libcalg.so.0
/home/vagrant/c-algorithms/src/.libs/libcalg.so.0
/home/vagrant/c-algorithms/src/.libs/libcalg.so.0.0.0
/usr/local/lib/libcalg.so.0
/usr/local/lib/libcalg.so.0.0.0
```

**Comment by jamesalbert** [comment]
just for verification:
```
vagrant@vagrant:~/minisana$ echo $LD_LIBRARY_PATH
/usr/local/lib
vagrant@vagrant:~/minisana$ stoke testcase --config testcase.conf 
bin/mini: error while loading shared libraries: libcalg.so.0: cannot open shared object file: No such file or directory
vagrant@vagrant:~/minisana$ LD_LIBRARY_PATH="/usr/local/lib" stoke testcase --config testcase.conf 
bin/mini: error while loading shared libraries: libcalg.so.0: cannot open shared object file: No such file or directory
vagrant@vagrant:~/minisana$ echo $?
0
```

I also added the return code because I don't think a failed run should return success

**Comment by yzhao30** [comment]
Similar thing happened to me. It seems stoke has some problem find /usr/local/lib. In my case, I installed the library in both /usr/lib and /usr/lib64 to make the error gone. So maybe you can try create symbolic link in /usr/lib and /usr/lib64?

**Comment by jamesalbert** [comment]
Awesome, thanks man. I actually ended up abstracting out the use of the library, but thanks for replying back. I'm sure that would have worked. Closing the issue...
