### ISSUE TITLE
Jenkins is down

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#963]
This is not directly related to STOKE, but we should fix this to avoid undetected failures.  @bchurchill, do you know why Jenkins is offline?

**Comment by bchurchill** [comment]
Apparently a recent update applied automatically, and the new jenkins requires java 8.  I've installed it and it's back now.

**Comment by bchurchill** [comment]
It looks like it's been down for 2.5 months (either that or we haven't pushed anything in the last 2.5 months).  I'm running jobs now.

**Comment by bchurchill** [comment]
Well it was working, now it's down again.  I think it's having some pretty major problems.  We might want to just save our config files/data and perform a reinstall from scratch.  Or maybe even host it on another system (which we spoke about doing in the past).

**Comment by bchurchill** [comment]
Well, it came back by itself and now it's running our code (and passing).  Hopefully it'll stay this way...
