### ISSUE TITLE
instruction moves can crash STOKE

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#98]
On rare, but reproducible, occasions STOKE crashes during an instruction move.  It happens when there are many preserved registers, and this forces rl_pool.size(), rh_pool.size(), rb_pool.size(), etc. to zero.  Then in Transforms::get_write_op() we mod-out by these zero-values causing SIGFPE or otherwise.

I'm not sure the best way to fix this, but I would imagine this should just cause the instruction move to fail instead?

I'm about to create an issue- branch and add a testcase exhibiting one instance of the bug.

**Comment by shrin18** [comment]
> Actually, I'm way to tired to figure out how to write a testcase for this. But you can reproduce easily. Just put this into target.s:
> 
> > .text
> > .globl foo
> > .type foo, @function
> > foo:
> > movl %r12d, %esi
> > shrb $0x3, %sil
> > andl $0x7, %esi
> > addl $0x30, %esi
> > retq
> 
> Then run `stoke search --target target.s --def_in "{ %r12 }" --live_out "{ %rsi %r12 }" --instruction_mass 100 --preserve_regs "{ %rax %rbx %rcx %rdx %rdi %rbp %rsp %r8 %r9 %r11d %r14 %r15 %xmm0 %xmm1 %xmm2 %xmm3 %xmm4 %xmm5 %xmm6 %xmm7 }"`


Errors:

  --target <path/to/file.s>
      Error reading value: Failed to parse line 1: .text
      Message: No such opcode '.text' exists
      Failed to parse line 2: .globl foo
      Message: No such opcode '.globl' exists
      Failed to parse line 3: .type foo, @function
      Message: No such opcode '.type' exists
      Failed to parse line 4: foo:
      Message: No such opcode 'foo:' exists
      
Can you help to recognise why I am getting these error ? I am not able to parse the above code for target.s when passing either as testcase or as in the command **<<<stoke@773a5b4edac6:~/stoke/stoke/examples/tutorial/bins$ stoke search --target ~/stoke/stoke/examples/tutorial/bins/target.s --def_in "{ %r12 }" --live_out "{ %rsi %r12 }" --instruction_mass 100 --preserve_regs "{ %rax %rbx %rcx %rdx %rdi %rbp %rsp %r8 %r9 %r11d %r14 %r15 %xmm0 %xmm1 %xmm2 %xmm3 %xmm4 %xmm5 %xmm6 %xmm7 }">>>**

**Comment by stefanheule** [comment]
Can you try to take one of the *.s files that definitely works (e.g. one from the examples folder), and just replace the code portion?  I think our parser is pretty picky about what the input format is supposed to look like.

**Comment by shrin18** [comment]
Yeah it works. So does that mean I cannot test it with my own compiled files via g++. I either get  
FATAL ERROR: Target/rewrite and functions contain an undefined symbol error or FATAL ERROR: Unable to generate testcases!

--Regards, 
Shrinish Donde
