### ISSUE TITLE
build: Makefile shoud fail when ccache is not available

### ISSUE THREAD

**Issue by monperrus** [StanfordPL/stoke#980]
`make` silently fails when ccache is not available. it takes some tome to understand a number of error messages afterwards, even if `bin/stoke` is present.

it would be nice if `./configure` or `make` fail when ccache is not available

**Comment by eloj** [comment]
If anything it should work without `ccache` to begin with.

**Comment by monperrus** [comment]
> it should work without |ccache|
|According to my experiment, it seems it's not the case.|

**Comment by stefanheule** [comment]
At the moment our Makefile includes ccache, but it would be good to have the script fail early and clearly if ccache is not installed.

I don't think there is a fundamental reason that we would require ccache, we have just always used it in the past.

**Comment by bchurchill** [comment]
Perhaps our config script can quickly check for its existence or
not-existence, save it in a variable, and then have the makefile use that?

**Comment by bchurchill** [comment]
Closing since we're packaging this with docker now.  If this is something one wants to fix, a pull request is welcome.
