### ISSUE TITLE
Implementing vpshufb

### ISSUE THREAD

**Issue by sdasgup3** [StanfordPL/stoke#981]
Currently there does not seem to be a way to extract the unsigned/signed value of a  bitvector. This is useful for implementing instructions like `vpshufb` which uses a bitvector to index another bitvector. Is this not implemented because of potential promlems that may arise while doing the smt solving?

**Comment by stefanheule** [comment]
No, I imagine it's not implemented simply because nobody has needed that instruction so far.  I don't see a reason why extracting the sign bits should be difficult for an SMT solver.

**Comment by sdasgup3** [comment]
Thanks! Just to be clear: I meant any practical issues that you might have  faced  due to changing the solver theory from Bitvector to Int. But anyway you clarify my doubts.

**Comment by stefanheule** [comment]
Okay, I guess I'm confused then.  We never use ints (as in mathematical integers) in our specifications, they are all expressed as bitvector formulas (because that's what CPUs compute over).

**Comment by bchurchill** [comment]
To add, we have implementations for other pshuf variants.  It wouldn't take
much work to add pshufb.  No need for the theory of integers.
