### ISSUE TITLE
Semantic bugs

### ISSUE THREAD

**Issue by sdasgup3** [StanfordPL/stoke#983]
Hello Stoke Team,
The followings seem to be bugs in the implementation of instruction semantics:

| Instruction | Bug | Suggestion|
|-------------|--------|-----------------|
|      addsubpd       |     Order of uninterpreted funcions f and g should be reversed.    | https://github.com/StanfordPL/stoke/pull/984| 
|      addsubps       |     -same-   | https://github.com/StanfordPL/stoke/pull/984|
|         (v)psll\<width\> family*  | The count operand should not be vectorized       | https://github.com/StanfordPL/stoke/pull/984. The behaviour of ymm_ymm_xmm cannot be properly handled in packed handler, so in the suggestion code the implementation is done in simple handler. |
|         (v)psrl\<width\> family**  | -same-       | -same- | 
|  vcvtsi2s\<precision\>\<width\> family*** |  The semantics of SSE and AVX versions are different in the sense that for the avx version, the bits (127:64) of the XMM register destination are copied from the corresponding bits in the first source operand.  | https://github.com/StanfordPL/stoke/pull/984. Because of he difference in semantics  of sse and avx versons, there is liitle point in keeping it in packed hadler, where we usually used to get the avx version semantics  for free| 

*** vcvtsi2s\<precision\>\<width\> family
```
vcvtsi2ssl
vcvtsi2ssq
vcvtsi2sdl
vcvtsi2sdq
```

\* (v)psll\<width\> family
```
pslld_xmm_xmm
vpslld_xmm_xmm_xmm
vpslld_ymm_ymm_xmm
psllq_xmm_xmm
vpsllq_xmm_xmm_xmm
vpsllq_ymm_ymm_xmm
psllw_xmm_xmm
vpsllw_xmm_xmm_xmm
vpsllw_ymm_ymm_xmm
```
** (v)psrl\<width\> family 
```
psrld_xmm_xmm
vpsrld_xmm_xmm_xmm
vpsrld_ymm_ymm_xmm
psrlq_xmm_xmm
vpsrlq_xmm_xmm_xmm
vpsrlq_ymm_ymm_xmm
psrlw_xmm_xmm
vpsrlw_xmm_xmm_xmm
vpsrlw_ymm_ymm_xmm
```

**Comment by stefanheule** [comment]
Fixed by #984
