### ISSUE TITLE
Ways to access encoded x64 in cost function?

### ISSUE THREAD

**Issue by sabastiaan** [StanfordPL/stoke#989]
Is there any way to access the actual executing bytes for a given function? 

From what I can tell the Instruction class does not expose its encoded format, and TUnit does provide a RIP offset of a file, but I'm unsure how to use that.

PS: Sorry if this not the correct place to ask this question

Thanks in advance,

Sebastiaan

**Comment by bchurchill** [comment]
See src/cost/binsize.h for an example.  Basically it's required to
reassemble the instruction stream; the sandbox adds a lot of
instrumentation that needs to be removed.
