### ISSUE TITLE
Undefined references with cvc4

### ISSUE THREAD

**Issue by pmatos** [StanfordPL/stoke#993]
After following all the instructions to build stoke and getting it done in a docker image of ubuntu 16.04 I am getting issues linking cvc4:
```
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::get_model_bv(std::string const&, unsigned short)':
cvc4solver.cc:(.text+0x54a2): undefined reference to `CVC4::IllegalArgumentException::format_extra(char const*, char const*)'
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::is_sat(std::vector<stoke::SymBool, std::allocator<stoke::SymBool> > const&)':
cvc4solver.cc:(.text+0x603d): undefined reference to `CVC4::Result::toString() const'
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::ExprConverter::build_function(stoke::SymBitVectorFunction const*)':
cvc4solver.cc:(.text+0x6eb3): undefined reference to `CVC4::ExprManager::mkVar(std::string const&, CVC4::Type, unsigned int)'
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::ExprConverter::visit(stoke::SymBitVectorVar const*)':
cvc4solver.cc:(.text+0x7743): undefined reference to `CVC4::ExprManager::mkVar(std::string const&, CVC4::Type, unsigned int)'
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::ExprConverter::visit(stoke::SymBoolVar const*)':
cvc4solver.cc:(.text+0x7898): undefined reference to `CVC4::ExprManager::mkVar(std::string const&, CVC4::Type, unsigned int)'
src/solver/cvc4solver.o: In function `stoke::Cvc4Solver::ExprConverter::visit(stoke::SymArrayVar const*)':
cvc4solver.cc:(.text+0x7aa1): undefined reference to `CVC4::ExprManager::mkVar(std::string const&, CVC4::Type, unsigned int)'
collect2: error: ld returned 1 exit status
Makefile:434: recipe for target 'bin/stoke_extract' failed
make[1]: *** [bin/stoke_extract] Error 1
```

**Comment by bchurchill** [comment]
I believe we have a --no-cvc4 option in our configure script.  Does that solve it?  I apologise we haven't invested in packaging STOKE nicely yet.

**Comment by pmatos** [comment]
@bchurchill That seems to work but then `make test` fails with 
```
In file included from ././tests/tests.h:71:0,
                 from tools/apps/stoke_test.cc:19:
././tests/validator/bounded.h: In constructor 'stoke::BoundedValidatorBaseTest::BoundedValidatorBaseTest()':
././tests/validator/bounded.h:43:20: error: expected type-specifier before 'Cvc4Solver'
       solver = new Cvc4Solver();
                    ^
compilation terminated due to -Wfatal-errors.
```

**Comment by bchurchill** [comment]
That's good to know.  We can keep this ticket open to fix this but it
probably won't happen soon.  To be honest, I'd just skip running the tests
for now.  If you're able to get the binaries to compile you should be in
good shape to get started.  If you really want to run the tests you can
replace all instances of Cvc4Solver with Z3Solver.

**Comment by jberryman** [comment]
@pmatos sorry to hijack thread, but do you have a dockerfile you can share for building STOKE?

**Comment by bchurchill** [comment]
By happenstance I just started working on this today for a PLDI artifact (although the paper has little to do with stoke itself!).  Stay tuned and ping me if you don't hear back in the next 10 days or so.

**Comment by pmatos** [comment]
@jberryman not a dockerfile per se but I have these instructions:
https://gitlab.linki.tools/snippets/15

**Comment by bchurchill** [comment]
Just a brief update -- I'm working on getting travis to automatically build a docker image for us from a docker file.  It's coming!  Stay tuned.

**Comment by bchurchill** [comment]
Should be set!  I've tested the haswell image is working (still doing a little bit of work on the sandybridge one).  Either way, the dockerfile is ready to go.
